---
version: "2.0"
services:
  app:
    image: ubuntu:20.04   
    env:
      - "SSH_PASS="
      - "MNEMONIC=" 
      - "MNEMONIC_BASE64="
      - "NETWORK_JSON_LINK="
      - "NETWORK_LOCAL_JSON_LINK="
      - "CRONTAB=0 21 * * *"
      - "RUN_ARG="
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ;
        apt-get upgrade -y ;
        apt-get install -y curl; curl -s https://raw.githubusercontent.com/eco-stake/restake/master/AkashNetwork/main.sh | bash '    
    expose:
      - port: 22
        as: 22
        to:
          - global: true 
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          size: 1Gi         
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
